### ISSUE TITLE
Handlers in css carousel

### ISSUE THREAD

**Issue by Lennervald** [Lennervald/e-handel#2]
When in mobile view, handlers (small circles) need more padding to its containers bottom border. See image.
![image](https://cloud.githubusercontent.com/assets/11617929/20641811/57e23eae-b400-11e6-92b7-0f4ff4cb3409.png)

**Comment by OlaJFrick** [comment]
Skumt så ser det inte ut på min, de har rätt perfekt padding. Men kanske olika i olika browsers.

**Comment by Lennervald** [comment]
märkligt, vilken browser kör du? Jag kör chrome

**Comment by OlaJFrick** [comment]
Chrome och Firefox 
![screenshot - 2016-11-28 11_25_15](https://cloud.githubusercontent.com/assets/21312250/20664874/6d9ffe44-b55d-11e6-9795-d2660fbf0d3b.png)

**Comment by Lennervald** [comment]
Har du testat i mobil-vy. Det är där jag får problem :)

**Comment by OlaJFrick** [comment]
Ja ok, samma här i mobile. 
Känns lite som nån bootstrapdefault som kan bli jobbig att fixa. men om du vill försök gärna.

**Comment by pellehardstedt** [comment]
fixat med mediaqueries i main.less
