### ISSUE TITLE
Renskriva Koden

### ISSUE THREAD

**Issue by OlaJFrick** [Lennervald/e-handel#25]
Gå genom och förbättra Koden: 

Thomas skulle lägga upp en text om hans "VG" kriterier

- Släng bort allt onödigt (oanvända klasser osv) som ligger kvar
- Rätt Indentering 
- Se över less filen, och skriva den med "korrekt" stil.

**Comment by Lennervald** [comment]
Även ändra texterna till antingen svenska eller engelska. :)

**Comment by OlaJFrick** [comment]
Ja, bra!

**Comment by OlaJFrick** [comment]
Enklast om en och var tar "sin" sektion av koden och renskriver, istället för att en gör allt?

**Comment by Lennervald** [comment]
Låter bra.

**Comment by OlaJFrick** [comment]
Jag kan ta på mig att renskriva main.less filen - för den är huller om buller nu. Blir oundvikligt för jag ska in med en del ny less för layouten.

**Comment by Lennervald** [comment]
ok
