### ISSUE TITLE
 Positioning of "buy now"-button

### ISSUE THREAD

**Issue by Lennervald** [Lennervald/e-handel#3]
**What's the best way to position the "buy now" button so that it works in all views, desktop -> mobile.**
![image](https://cloud.githubusercontent.com/assets/11617929/20641882/0a00c816-b402-11e6-8dc5-c0007539bcc1.png)

**Comment by pellehardstedt** [comment]
"read more" och "buy more" knapparna är nu på en egen rad, vänsterställt under produktnamn och pris! Funkar?
