### ISSUE TITLE
Hype area bör återspegla förslagsvis fyndvaror eller annan kategori som är passande

### ISSUE THREAD

**Issue by Lennervald** [Lennervald/e-handel#32]

**Comment by OlaJFrick** [comment]
Hade det i själva wireframen, eller tänke ni på annat sätt?
![fynd](https://cloud.githubusercontent.com/assets/21312250/20749315/1de0ea1c-b6f2-11e6-860a-6a619cb4c0f5.png)

**Comment by Lennervald** [comment]
Nej, det var så vi tänkte, men missade kolla i wireframen :)
