### ISSUE TITLE
Desktop View - "Search"?

### ISSUE THREAD

**Issue by OlaJFrick** [Lennervald/e-handel#8]
Solve the problem how to display the "search" in Desktop view.

**Comment by OlaJFrick** [comment]
Känns mest naturligt att lägga search till vänster om Hamburgaren ( i Mobile View ). Vad tycker ni?

**Comment by Lennervald** [comment]
Ja, det håller jag med om

**Comment by Lennervald** [comment]
Se branch "combine-top-nav-menu" för förslag på lösning
